background = #030407
foreground = #dad7d3
cursor-color = #faf8f6
selection-background = #002847
selection-foreground = #faf8f6

palette = 0=#030407
palette = 1=#a8836d
palette = 2=#707c25
palette = 3=#707c2a
palette = 4=#208cde
palette = 5=#2b8cda
palette = 6=#268cdc
palette = 7=#dad7d3
palette = 8=#435e75
palette = 9=#c79e85
palette = 10=#8a983b
palette = 11=#8a983f
palette = 12=#45a9fd
palette = 13=#43aaff
palette = 14=#41a9ff
palette = 15=#faf8f6
