foreground #dad7d3
background #030407
selection_foreground #faf8f6
selection_background #002847

cursor #faf8f6
cursor_text_color #030407

active_border_color #b2b632
active_tab_background #b2b632

color0 #030407
color1 #a8836d
color2 #707c25
color3 #707c2a
color4 #208cde
color5 #2b8cda
color6 #268cdc
color7 #dad7d3
color8 #435e75
color9 #c79e85
color10 #8a983b
color11 #8a983f
color12 #45a9fd
color13 #43aaff
color14 #41a9ff
color15 #faf8f6
